name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 7 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        scala: [2, 3]
        project: [rootJVM, rootJS, rootNative]
        java: [8]
        include:
          - java: 11
            scala: 2
            project: rootJVM
          - java: 25
            scala: 2
            project: rootJVM
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        java-version: ${{matrix.java}}
        distribution: zulu
    - uses: coursier/cache-action@v7
    - run: ./sbt -v
           -Dcheck_build_file_imports
           checkGenTypeClasses
           $(if [[ "${{ matrix.scala }}" == "3" ]]; then echo SetScala3; fi)
           "project ${{ matrix.project }}"
           Test/compile
           $(if [[ "${ matrix.project }}" == "rootJS" ]]; then echo "Test/fastOptJS"; fi)
    - run: ./sbt -v
           $(if [[ "${{ matrix.scala }}" == "3" ]]; then echo SetScala3; fi)
           "project ${{ matrix.project }}"
           test
           "project /"
           $(if [[ "${{ matrix.project }}" == "rootJVM" ]]; then echo "publishLocal"; fi)
    - run: |
        case ${{ matrix.project }} in
          "rootJVM")
            ./sbt -v \
               $(if [[ "${{ matrix.scala }}" == "3" ]]; then echo SetScala3; fi) \
               "project exampleJVM" \
               runAllMain
            ;;
          "rootJS")
            ./sbt -v \
               $(if [[ "${{ matrix.scala }}" == "3" ]]; then echo SetScala3; fi) \
               "project exampleJS" \
               runAllMain
            ;;
          "rootNative")
            ./sbt -v \
               $(if [[ "${{ matrix.scala }}" == "3" ]]; then echo SetScala3; fi) \
               "project exampleNative" \
               runAllMain
            ;;
          *)
            echo "unknown project"
            exit 1
        esac
    - uses: mikepenz/action-junit-report@e08919a3b1fb83a78393dfb775a9c37f17d8eea6 # v6.0.1
      if: always()
      with:
        report_paths: '**/target/test-reports/*.xml'
        require_tests: true
        check_name: "${{ matrix.java }}-${{ matrix.scala }}-${{ matrix.project }}"
    - uses: test-summary/action@v2
      if: always()
      with:
        paths: '**/target/test-reports/*.xml'
    - run: rm -rf "$HOME/.ivy2/local" || true
  latest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        java-version: 25
        distribution: zulu
    - uses: coursier/cache-action@v7
    - id: scala_3_version
      run: echo "value=$(cat .github/scala_3_latest.txt)" >> $GITHUB_OUTPUT
    - run: ./sbt -v
           "++ ${{ steps.scala_3_version.outputs.value }}!"
           Test/compile
  wasm:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        java-version: 25
        distribution: zulu
    - uses: actions/setup-node@v6
      with:
        node-version: 22
    - uses: coursier/cache-action@v7
    - run: ./sbt -v
           -Dscala_js_wasm
           rootJS/Test/compile
           testsJS/test
    - run: ls -l "tests/js/target/scala-2.13/scalaz-tests-test-fastopt/main.wasm"
    - run: ls -l "tests/js/target/scala-2.13/scalaz-tests-test-fastopt/"
