name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 2 * * *'
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        scala: [2_12, 2_13, 3]
        project: [rootJVM, rootJS, rootNative]
        java: [8]
        include:
          - scala: 2_13
            project: rootJVM
            java: 17
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - run: |
        sbt -v \
        checkGenTypeClasses \
        "project ${{ matrix.project }}" \
        "SetScala${{ matrix.scala }}" \
        "Test/compile" \
        "mimaReportBinaryIssues" \
        $(if [[ "${ matrix.project }}" == "rootJS" ]]; then echo "Test/fastOptJS"; fi)
    - run: |
        sbt -v \
        "project ${{ matrix.project }}" \
        "SetScala${{ matrix.scala }}" \
        "test" \
        "project /" \
        $(if [[ "${{ matrix.project }}" == "rootJVM" ]]; then echo "publishLocal"; fi)
    - run: |
        case ${{ matrix.project }} in
          "rootJVM")
            ./sbt -v \
               "SetScala${{ matrix.scala }}" \
               "project exampleJVM" \
               runAllMain
            ;;
          "rootJS")
            ./sbt -v \
               "SetScala${{ matrix.scala }}" \
               "project exampleJS" \
               runAllMain
            ;;
          "rootNative")
            ./sbt -v \
               "SetScala${{ matrix.scala }}" \
               "project exampleNative" \
               runAllMain
            ;;
          *)
            echo "unknown project"
            exit 1
        esac
    - if: always()
      run: rm -rf "$HOME/.ivy2/local" || true
